name = "kpmcs forge client 8-9-25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28535c327d6f60b52188c63fa1befbfd7ae293201e64fdfc5d042f7e209e3397"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
