name = "kpmcs forge client 8-9-25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c84e29850ec06e2a7feaf0e16ac20f403b2aa8b74c63d6fb970e6c4498bebef"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
