name = "kpmcs forge client 8-9-25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53ef09af907eef8e09890bf799993943f27d14535a5089d81cd0b4c41739ae1c"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
