name = "kpmcs forge client 8-9-25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16166eb029c5b715b8ed47ad40b701b320eab466c26b4a1dcd97c0ff4b35f562"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
